<!DOCTYPE html>
<html lang="en">
<head>
    <title id='Description'>The jqxTree displays a hierarchical collection of items. You
        can populate it from 'UL' or by using its 'source' property.</title>
    <link rel="stylesheet" href="jqwidgets/jqwidgets/styles/jqx.base.css" type="text/css" />
    <link rel="stylesheet" href="jqwidgets/jqwidgets/styles/jqx.summer.css" type="text/css" />
    <script type="text/javascript" src="jqwidgets/scripts/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="jqwidgets/jqwidgets/jqxcore.js"></script>
    <script type="text/javascript" src="jqwidgets/jqwidgets/jqxbuttons.js"></script>
    <script type="text/javascript" src="jqwidgets/jqwidgets/jqxscrollbar.js"></script>
    <script type="text/javascript" src="jqwidgets/jqwidgets/jqxpanel.js"></script>
    <script type="text/javascript" src="jqwidgets/jqwidgets/jqxtree.js"></script>
    <script type="text/javascript" src="custom.js"></script>
    <script type="text/javascript">
        var tree = tree || false;
        $(document).ready(function () {
            var source = [
                <?php echo json_encode($this->getAllLevelChildren()); ?>
            ];
            // Create jqxTree.
            tree = $('#jqxTree').jqxTree({ source: source, height: '300px', width: '300px' });
        });
    </script>
</head>
<body class='default'>
<div id='jqxTree'>
</div>
</body>
</html>

